- name: install nginx
  hosts: node
  tasks:
  - name: nginx install
    ansible.builtin.package:
     name: nginx
     state: present

  - name: start and enable 
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes