- name: Variables from file
  hosts: local
  connection: local
  vars_file:
  - course.yaml
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course duration: {{ DURATION }}, Trainer is {{ TRAINER }}"