- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: USER 
    prompt: enter username
    private: false

  - name: PASSWORD
    prompt: enter password 
    private: true
  tasks:
  - name: print user info
    ansible.builtin.debug:
     msg: "Hello Username is: {{ USERNAME }}, password is: {{ PASSWORD }}"