- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: USER 
    prompt: enter username
    private: false # user can see what they are entering

  - name: PASSWORD
    prompt: enter password 
    private: true # user cannot see what they are entering
  tasks:
  - name: print user info
    ansible.builtin.debug:
     msg: "Hello Username is: {{ USER }}, password is: {{ PASSWORD }}"